version: '3.8'

services:
  app:
    image: your-app-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - insights-data:/app/data
    environment:
      - DB_PATH=/app/data/insights.db
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - insights-data:/var/lib/sqlite

volumes:
  insights-data:
    driver: local