version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5554:5432"

  app:
    build: .
    container_name: go_app
    environment:
       DB_HOST: ${DB_HOST}
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local