version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - insights-data:/app/data
    environment:
      - DB_PATH=/app/data/insights.db

volumes:
  insights-data:
    driver: local